# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'MagMemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!

  # Pods for MagMemo

rn_path = '../node_modules/react-native'
  pod 'FLAnimatedImage'
  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
    'CxxBridge'
  ]

  # Pods for OBWApp
  pod 'SVProgressHUD'
  pod 'LTMorphingLabel'
  pod 'SwiftyUserDefaults', '~> 4.0'
  pod 'IQKeyboardManagerSwift'
  pod 'Alamofire'
  
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'
  pod 'react-native-version-number', :path => '../node_modules/react-native-version-number'

  pod 'react-native-network-info', :path => '../node_modules/react-native-network-info'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'


  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'

  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
 
  pod 'JPushRN', :path => '../node_modules/jpush-react-native'
  pod 'JCoreRN', :path => '../node_modules/jcore-react-native'
  
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
  
  
end

# very important to have, unless you removed React dependencies for Libraries 
# and you rely on Cocoapods to manage it
#post_install do |installer|
#  installer.pods_project.targets.each do |target|
#    if target.name == "React"
#      target.remove_from_project
#    end
#  end
#end

